### ISSUE TITLE
Queries are not working anymore

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/polyflow-examples#116]
The usage of almost any query (possible using Axon Gateway Extension) delivers the following exception and no results:

This is the query for tasks...

```
org.axonframework.axonserver.connector.query.AxonServerQueryDispatchException: Query did not yield the expected number of results.
	at org.axonframework.axonserver.connector.query.AxonServerQueryBus$ResponseProcessingTask.run(AxonServerQueryBus.java:737) ~[axon-server-connector-4.5.10.jar:4.5.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

```

**Comment by zambrovski** [comment]
Works again.
